# External gems
# See http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html for making `jekyll archives` work.
plugins:
  #- jekyll-archives # Sorry, not GitHub pages friendly!
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Site settings
title: simfle@Dev
#subtitle: "A simple yet classy theme for your Jekyll website or blog"
email: badangapmg@gmail.com
name: badang
description: >
  A badang's blog.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://badangapmg.github.io" # the base hostname & protocol for your site
cover: "/assets/olympic-park.jpg"
logo: "/assets/home.png"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai-sublime"

# Archive settings (see https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'


descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: spring microservice
    desc: "Spring MicroService"

  - cat: kotlin
    desc: "Kotlin study"

  - cat: Kafka
    desc: "Kafka study"

  - cat: MongoDB
    desc: "MongoDB"

social:
  - name: GitHub
    icon: github
    username: badang
    url: https://github.com/badangapmg
    desc: Fork me on GitHub
    share: false

  - name: Google+
    icon: google-plus
    username: badangapmg@gmail.com
    url:
    desc: Add me to your Circles
    share: true

# Social sharing protocols
# These are for automatically generating sharing metadata for FB and Twitter
# OS Protocol is for sharing the source of your site, if you're interested. For more, see osprotocol.com
protocols:
  fb_image: "/assets/logo.png"
  fb_image_width: 612
  fb_image_height: 605
  fb_image_type: "image/png"
  twitter_image: "/assets/logo.png"
